data:
  source: imagefolder
  name: /home/hlcv_team015/datasets/guitar-chords-A-G
  transforms:
    train:
      - name: RandomResizedCrop
        params:
          size: [224, 224]
    base:
      - name: Resize
        params:
          size: [224, 224]
          
model:
  name: google/mobilenet_v2_1.0_224
  num_labels: 7

training:
  output_dir: ./output
  num_epochs: 10
  batch_size: 32
  learning_rate: 1e-4
  logging_dir: Project/src/cluster/logs
  logging_steps: 100
  early_stopping_patience: 3
  final_model_path: ./mobilenet_v2_final_model

wandb:
  run_name: mobilenet-v2
