model:
  name: faster_rcnn
  model_dir: ./original_models
  num_labels: 2
  trainable_backbone_layers: 1

training:
  output_dir: ./final_models/faster_rcnn/output
  num_epochs: 20
  batch_size: 8
  warmup_steps: 500
  weight_decay: 0.01
  learning_rate: 1e-4
  logging_dir: ./final_models/faster_rcnn/logs
  logging_steps: 100
  eval_strategy: epoch
  eval_steps: 50
  early_stopping_patience: 5