# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv10 object detection model with additional head
# Parameters
nc: 81  # number of classes (80 original + 1 new)
scales:
  l: [1.00, 1.00, 512]
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, SCDown, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, SCDown, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2fCIB, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9
  - [-1, 1, PSA, [1024]]  # 10
# YOLOv10 head with additional detection head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2fCIB, [512, True]]  # 13
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 16 (P3/8-small)
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2fCIB, [512, True]]  # 19 (P4/16-medium)
  - [-1, 1, SCDown, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2fCIB, [1024, True]]  # 22 (P5/32-large)

  - [[16, 19, 22], 1, Detect, [80]]  # Detect(P3, P4, P5) for original 80 classes
  - [[16, 19, 22], 1, Detect, [1]]   # Detect(P3, P4, P5) for 1 new class
  - [[23, 24], 1, ConcatHead, [80, 1]]  # Concat outputs from both detection heads