wandb:
  project_name: "fretboard-recognition"

model:
  name: "yolov8m"
  freeze_layers: -1

data:
  dataset: "guitar-necks-detector"
  load: 
    interface: "roboflow"
    workspace: "hubert-drapeau-qt6ae"
    project-version: "1"
    version-download: "yolov9"
  # dataset: "guitar-detection-2.0"
  # load:
  #   interface: "roboflow"
  #   workspace: "guitars"
  #   project-version: "1"
  #   version-download: "yolov9"

training:
  output_dir: "output"
  imgsz: 640
  epochs: 20