data:
  source: imagefolder
  name: /home/hlcv_team015/datasets/merged_ds

  additional_test_datasets:
    guitar_chords_tiny:
      name: /home/hlcv_team015/datasets/guitar-chords-tiny
      source: imagefolder
    guitar_chords_tiny_ours_A_G:
      name: /home/hlcv_team015/datasets/guitar-chords-A-G
      source: imagefolder

base_model: True

training:
  num_epochs: 20
  batch_size: 32
  learning_rate: 1e-5
  final_model_path: base_model

wandb:
  run_name: base_model
