# config.yaml
data:
  source: huggingface
  name: cifar10  # Example dataset, replace with your actual image dataset
  transforms:
    train:
      - name: RandomResizedCrop
        params:
          size: [224, 224]
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ColorJitter
        params:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.1
      - name: ToTensor
      - name: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    base:
      - name: Resize
        params:
          size: [224, 224]
      # - name: ToTensor
      # - name: Normalize
      #   params:
      #     mean: [0.485, 0.456, 0.406]
      #     std: [0.229, 0.224, 0.225]

model:
  name: google/vit-base-patch16-224  # Example model, replace with your preferred image classification model
  num_labels: 10  # Number of classes in your dataset

training:
  output_dir: ./output
  num_epochs: 3
  batch_size: 32
  warmup_steps: 500
  weight_decay: 0.01
  logging_dir: ./logs
  logging_steps: 100
  final_model_path: ./final_model

wandb:
  project: image-classification-finetune
  run_name: vit-base-cifar10