data:
  source: imagefolder
  name: /home/hlcv_team015/datasets/limited
  
  additional_test_datasets:
    guitar_chords_tiny:
      name: /home/hlcv_team015/datasets/guitar-chords-tiny
      source: imagefolder
    guitar_chords_tiny_ours_A_G:
      name: /home/hlcv_team015/datasets/guitar-chords-ours-A-G
      source: imagefolder
      
model:
  name: google/vit-large-patch32-224-in21k

training:
  num_epochs: 20
  batch_size: 32
  learning_rate: 2e-4
  final_model_path: vit-large-patch32-224-in21k_final_model

wandb:
  run_name: vit-large-patch32-224-in21k-guitar-chords
