data:
  source: imagefolder
  name: home/hlcv_team015/data
  transforms:
    train:
      - name: RandomResizedCrop
        params:
          size: [224, 224]
      - name: RandomHorizontalFlip
        params:
          p: 0.5
      - name: ColorJitter
        params:
          brightness: 0.2
          contrast: 0.2
          saturation: 0.2
          hue: 0.1  
      - name: ToTensor
      - name: Normalize
        params:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
    base:
      - name: Resize
        params:
          size: [224, 224]
          
model:
  name: google/vit-large-patch16-224-in21k
  num_labels: 14

training:
  output_dir: ./output
  num_epochs: 20
  batch_size: 16
  learning_rate: 1e-5
  logging_dir: ./logs
  logging_steps: 100
  early_stopping_patience: 5
  final_model_path: ./vit-large-patch16-224-in21k_final_model

wandb:
  run_name: vit-large-patch16-224-in21k-guitar-chords