data:
  source: imagefolder
  name: /home/hlcv_team015/datasets/merged_ds

  additional_test_datasets:
    guitar_chords_tiny:
      name: /home/hlcv_team015/datasets/guitar-chords-tiny
      source: imagefolder
    guitar_chords_tiny_ours_A_G:
      name: /home/hlcv_team015/datasets/guitar-chords-A-G
      source: imagefolder

model:
  name: facebook/dinov2-small

training:
  num_epochs: 20
  batch_size: 16
  learning_rate: 4e-4
  final_model_path: dinov2-small-final-model

wandb:
  run_name: dinov2-small